name: manage-azure-policy-7489a804
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'AzurePolicy/initiatives/Ahmanet-Policy-Set_77359cd1d1f6488a89ccb1ce/**'
#      - .github/workflows/manage-azure-policy-7489a804.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7489a804}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          AzurePolicy/initiatives/Ahmanet-Policy-Set_77359cd1d1f6488a89ccb1ce/**
